// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadSettings():Promise<any>;

export function OpenConfigFolder(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:string):Promise<boolean>;
