// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadCategories() {
  return window['go']['main']['App']['LoadCategories']();
}

export function LoadLabels() {
  return window['go']['main']['App']['LoadLabels']();
}

export function LoadQuestions() {
  return window['go']['main']['App']['LoadQuestions']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenConfigFolder(arg1) {
  return window['go']['main']['App']['OpenConfigFolder'](arg1);
}

export function SaveCategories(arg1) {
  return window['go']['main']['App']['SaveCategories'](arg1);
}

export function SaveLabels(arg1) {
  return window['go']['main']['App']['SaveLabels'](arg1);
}

export function SaveQuestions(arg1) {
  return window['go']['main']['App']['SaveQuestions'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
