// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function LoadCategories():Promise<any>;

export function LoadLabels():Promise<any>;

export function LoadQuestions():Promise<any>;

export function LoadSettings():Promise<any>;

export function OpenConfigFolder(arg1:string):Promise<boolean>;

export function SaveCategories(arg1:string):Promise<boolean>;

export function SaveLabels(arg1:string):Promise<boolean>;

export function SaveQuestions(arg1:string):Promise<boolean>;

export function SaveSettings(arg1:string):Promise<boolean>;
